version: '3.8'

services:
  web:
    build: .
    command: >
       sh -c "uvicorn main:app --reload"

    environment:
      - "ENGINE=django.db.backends.postgresql"
      - "DBNAME=postgres"
      - "US=postgres"
      - "PS=postgres"
      - "HOST=db"
      - "PORT=5432"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: