apiVersion: v1
kind: Service
metadata:
  name: fast-api-nodeport
spec:
  type: NodePort
  selector:
    app: api-cars-1
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30800